# Generated by Django 3.0.5 on 2021-02-24 20:10

from django.db import migrations, models
import docxApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('file', models.FileField(upload_to=docxApp.models.get_path)),
            ],
        ),
    ]
